miscal_max_angle_deg: null
miscal_max_translation_m: null
orbital_miscal_noise_level: null
orbital_miscal_noise_levels: null
cotrain_miscal_group_ids: null
cotrain_miscal_level: null
cotrain_miscal_levels: null
